# Generated by Django 3.2.6 on 2021-08-09 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('liste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jury_number', models.PositiveIntegerField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('school_affected', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=30)),
                ('grades', models.DecimalField(decimal_places=3, max_digits=6)),
                ('appreciations', models.CharField(max_length=100)),
                ('liste', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='liste.liste')),
            ],
        ),
    ]
