# Generated by Django 3.2.6 on 2021-08-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jury',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='jury',
            name='phone_number',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
