# Generated by Django 3.2.6 on 2021-08-14 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jury', '0002_auto_20210814_1213'),
        ('liste', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grades', models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True)),
                ('appreciations', models.CharField(default=0, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('jury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jury.jury')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liste.liste')),
            ],
        ),
    ]
