# Generated by Django 3.2.6 on 2021-08-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liste', '0002_liste_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liste',
            name='student_number',
            field=models.IntegerField(),
        ),
    ]
